<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Show;
use AppBundle\Type\ShowType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class ShowController
 * @package AppBundle\Controller
 * @Route("/show")
 */
class ShowController extends Controller
{
    /**
     * @Route("/", name="list_show")
     */
    public function listAction() {

        $repository = $this->getDoctrine()->getRepository(Show::class);

        $shows = $repository->findAll();


        return $this->render('show/list.html.twig', [
            'list_shows' => $shows,
            'default_image' => $this->getParameter('picture_show_directory').'/default.jpg'
        ]);
    }

    /**
     * @Route("/create", name="create_show")
     */
    public function createAction(Request $request) {

        $form = $this->createForm(ShowType::class);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $show = $form->getData();

            $file = $show->getPathMainPicture();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // Move the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('picture_show_directory'),
                $fileName
            );
            $show->setPathMainPicture($fileName);


            // for example, if Task is a Doctrine entity, save it!
            $em = $this->getDoctrine()->getManager();
            $em->persist($show);
            $em->flush();

            return $this->redirectToRoute('list_show');
        }

        return $this->render('show/create.html.twig', ['form' => $form->createView()]);

    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    public function categoriesAction() {
        return $this->render('show/categories.html.twig', [
            'categories' => ['Web design', 'HTML', 'Freebies', 'Javascript', 'CSS', 'Tutorials']
        ]);
    }
}
