app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_api:
    resource: '@AppBundle/API/Controller/'
    prefix: /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }