<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
    public function findAllByQuery($query)
    {
        return $this->createQueryBuilder('s')
            ->where('LOWER(s.name) LIKE :query')
            ->setParameter('query', '%' . $query . '%')
            ->getQuery()
            ->getResult()
            ;
    }
}
